# Generated by Django 5.1.4 on 2024-12-12 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_alter_book_book_add_date_alter_book_book_add_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2024, 12, 12, 13, 50, 36, 420065, tzinfo=datetime.timezone.utc)),
        ),
    ]
